# Generated by Django 5.1.1 on 2024-09-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calories', models.IntegerField()),
                ('protein', models.FloatField()),
                ('fats', models.IntegerField()),
                ('carbs', models.FloatField()),
            ],
        ),
    ]
