# Generated by Django 5.1.1 on 2024-09-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calariecount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='fats',
            field=models.FloatField(),
        ),
    ]
